<?php
session_start();
if ($_SESSION['role'] != 'admin') {
    
    echo "<h3>Not Allowed !</h3>";
    die;
}

?>
<a href="/product/add/" class="btn btn-info m-3">Add Products!</a>
<a href="/product/index/" class="btn btn-info m-3">Display Products!</a>
<a href="/login/index/" class="btn btn-info m-3">Login!</a>
<a href="/place/new/" class="btn btn-info m-3">Place Order!</a>
<a href="/place/display" class="btn btn-info m-3">Display Orders!</a>
<section class="vh-100">
    <div class="container-fluid h-custom">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">

                <form action = '/product/addnew' method = 'POST'>

                 <!-- id input -->
                 <div class="form-outline mb-4">Product-ID
                        <input type="text" id="form3Example3" class="form-control form-control-lg"
                            placeholder="Enter your pid" name='id' />
                    </div>

                    <!-- name input -->
                    <div class="form-outline mb-4">Product-Name
                        <input type="text" id="form3Example3" class="form-control form-control-lg"
                            placeholder="Enter your name" name='name' />
                    </div>

                    <!-- type input -->
                    <div class="form-outline mb-3">Product-Type
                        <input type="text" id="form3Example4" class="form-control form-control-lg"
                            placeholder="Enter your type" name='type' />
                    </div>

                    <!-- enter a price -->
                    <div class="form-outline mb-3">Price
                        <input type="number" id="form3Example4" class="form-control form-control-lg"
                            placeholder="Enter price" name='price' />
                    </div>


                    <div class="text-center text-lg-start mt-4 pt-2">
                        <input type="submit" class="btn btn-primary btn-lg"
                            style="padding-left: 2.5rem; padding-right: 2.5rem;" value = 'Add Product'>

                    </div>

                </form>
            </div>
        </div>
    </div>

</section>