<?php
session_start();
if ($_SESSION['role'] != 'admin') {
    
    echo "<h3>Not Allowed !</h3>";
    die;
}

?>
<a href="/product/add/" class="btn btn-info m-3">Add Products!</a>
<a href="/product/index/" class="btn btn-info m-3">Display Products!</a>
<a href="/login/index/" class="btn btn-info m-3">Login!</a>
<a href="/place/new/" class="btn btn-info m-3">Place Order!</a>
<a href="/place/display" class="btn btn-info m-3">Display Orders!</a>


<?php
echo "<div class='row'>";
foreach ($data as $value) {
    echo "<div class='card ' style='width: 18rem;'>
<div class='card-body'>
  <h5 class='card-title'>Name : $value->name</h5>
  <h6 class='card-subtitle mb-2 text-muted'>Type :  $value->type</h6>
  <h4 > Price : $value->price</h4>
  <a href='/product/edit/?id=$value->id' class='card-link'>Edit</a>
  <a href='/product/delete/?id=$value->id' class='card-link'>Delete</a>
</div>
</div>";
}
echo "</div>";
?>